[package]

name = "yaxpeax-x86"
version = "0.0.1"
authors = [ "iximeow <me@iximeow.net>" ]
repository = "x86-rs"
description = """
A rust x86-64 decoder
"""

[dependencies]
"num-traits" = "0.2"
"termios" = "0.2.2"
"termion" = "1.4.0"
"serde" = "*"
"serde_json" = "*"
"serde_derive" = "*"

[[test]]
name = "test"
path = "test/test.rs"

[[bench]]
name = "bench"
path = "test/bench.rs"

[profile.bench]
opt-level = 3
lto = true

[profile.release]
opt-level = 3
lto = true

[features]
default = []

# This enables some capstone benchmarks over the same
# instruction bytes used to bench this code.
capstone_bench = []
